/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo/index'
import { Route as DemoApiRouteImport } from './routes/demo/api'
import { Route as DemoBingImgRouteImport } from './routes/demo/bing/img'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/demo/',
  path: '/demo/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiRoute = DemoApiRouteImport.update({
  id: '/demo/api',
  path: '/demo/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBingImgRoute = DemoBingImgRouteImport.update({
  id: '/demo/bing/img',
  path: '/demo/bing/img',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/api': typeof DemoApiRoute
  '/demo': typeof DemoIndexRoute
  '/demo/bing/img': typeof DemoBingImgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/api': typeof DemoApiRoute
  '/demo': typeof DemoIndexRoute
  '/demo/bing/img': typeof DemoBingImgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/api': typeof DemoApiRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/bing/img': typeof DemoBingImgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/demo/api' | '/demo' | '/demo/bing/img'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/demo/api' | '/demo' | '/demo/bing/img'
  id: '__root__' | '/' | '/demo/api' | '/demo/' | '/demo/bing/img'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoApiRoute: typeof DemoApiRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoBingImgRoute: typeof DemoBingImgRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api': {
      id: '/demo/api'
      path: '/demo/api'
      fullPath: '/demo/api'
      preLoaderRoute: typeof DemoApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/bing/img': {
      id: '/demo/bing/img'
      path: '/demo/bing/img'
      fullPath: '/demo/bing/img'
      preLoaderRoute: typeof DemoBingImgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoApiRoute: DemoApiRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoBingImgRoute: DemoBingImgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
